// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
// import 'firebase_options.dart';

// ...

// await Firebase.initializeApp(
// options: DefaultFirebaseOptions.currentPlatform,
// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCpYk6BqGjZLQKkoEj3XZHOSTpLPC0lUws',
    appId: '1:975927484167:web:ec9de0c070d8c5a44aafa2',
    messagingSenderId: '975927484167',
    projectId: 'phoneauthflutter-25aa0',
    authDomain: 'phoneauthflutter-25aa0.firebaseapp.com',
    storageBucket: 'phoneauthflutter-25aa0.appspot.com',
    measurementId: 'G-2Y09QRPWB4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCIDvhWVOx_IWanXeHLJk4Bsj5YUKJPSbc',
    appId: '1:975927484167:android:6ce7f41e0bf579c84aafa2',
    messagingSenderId: '975927484167',
    projectId: 'phoneauthflutter-25aa0',
    storageBucket: 'phoneauthflutter-25aa0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBU_1LeVxkJwOxzX61lcKBMmzlcjkFGR6s',
    appId: '1:975927484167:ios:45e2dc0e5b1be5114aafa2',
    messagingSenderId: '975927484167',
    projectId: 'phoneauthflutter-25aa0',
    storageBucket: 'phoneauthflutter-25aa0.appspot.com',
    iosBundleId: 'com.example.liveasy',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBU_1LeVxkJwOxzX61lcKBMmzlcjkFGR6s',
    appId: '1:975927484167:ios:6f3ed78ad96c716b4aafa2',
    messagingSenderId: '975927484167',
    projectId: 'phoneauthflutter-25aa0',
    storageBucket: 'phoneauthflutter-25aa0.appspot.com',
    iosBundleId: 'com.example.liveasy.RunnerTests',
  );
}
